# Generated by Django 2.0.5 on 2020-07-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200725_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': '单元', 'verbose_name_plural': '单元'},
        ),
        migrations.AlterModelTable(
            name='module',
            table='module',
        ),
    ]
