# Generated by Django 2.0.5 on 2020-07-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='教学文件'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='images', verbose_name='教学图片'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(verbose_name='教学文本'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(verbose_name='教学视频url'),
        ),
    ]
